'use client';

import { Theme, ThemePanel } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { persistor, store } from '@/redux/store';
import { Toaster } from 'react-hot-toast';
import { Jersey, inter } from './assets/fonts';
import './styles/globals.css';

import Header from './components/layout/Header';
import Sidebar from './components/layout/SideBar';
import MusicPlayer from './components/MusicPlayer/MusicPlayer';
import SimpleTextLoading from './components/layout/SimpleTextLoading';
import MobileBottomNavigation from './components/layout/MobileBottomNavigation';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const title = metadata.title ? String(metadata.title) : 'Default Title';
  const description = metadata.description ? String(metadata.description) : 'Default description';

  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <title>{title}</title>
        <meta name="description" content={description} />
      </head>
      <body className={`${inter.className} ${Jersey.className} relative h-screen  bg-accent_8`}>
        <Provider store={store}>
          <PersistGate loading={<SimpleTextLoading />} persistor={persistor}>
            <ThemeProvider attribute="class">
              <Theme accentColor="indigo" grayColor="sand" radius="medium" scaling="95%">
                <Toaster />
                <Header />
                <div className="flex">
                  <Sidebar />
                  <div className="relative min-h-[calc(100vh_-_80px)] w-full max-w-screen-2xl  p-4 lg:pl-[226px]">
                    {children}
                  </div>
                </div>
                <MusicPlayer />
                <MobileBottomNavigation />
                <ThemePanel />
              </Theme>
            </ThemeProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
